name: deploy-staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
  
    strategy:
      matrix:
        node-version: [16.14.x]

    steps:
      - name: Checkout Github-Actions
        uses: actions/checkout@v2

      - name: Install node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm install

      - name: Start Build with npm
        run: npm run bhild
        env:
          CI: false

      - name: Setting for AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: aws deploy push --application-name debrains --description "Debraions Test" --s3-location s3://debrain.co.kr/deploy/debrains-staging.zip --source .

      - name: Start Deploy with CodeDeploy
        run: aws deploy create-deployment --application-name debrains --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name debrains-staging --s3-location bucket=debrain.co.kr,bundleType=zip,key=deploy/debrains-staging.zip


